language: minimal

env:
  - PWSHFW_VERSION=3.0.3.357

matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   addons:
    #     apt:
    #       sources:
    #         - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
    #           key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    #       packages:
    #         - fakeroot
    #         - powershell
    #       update: true
    - os: linux
      dist: bionic
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - fakeroot
            - powershell
          update: true
      before_install:
        - pwd
        - echo "Pass 01 before_install [linux/bionic]"
        - wget https://github.com/cadegenn/pwsh_fw/releases/latest/download/pwshfw-$PWSHFW_VERSION-all.deb
        - ls -aldFh
        - sudo dpkg -i ./pwshfw-$PWSHFW_VERSION-all.deb
    - os: osx
      osx_image: xcode10
      before_install:
        - echo "Pass 01 before_install [osx/xcode10]"
        - brew tap caskroom/cask
        - brew cask install powershell
        # - brew install wget # already installed
        - wget https://github.com/cadegenn/pwsh_fw/releases/latest/download/Tiny.PowerShell.Framework-$PWSHFW_VERSION.pkg
        - sudo installer -pkg Tiny.PowerShell.Framework-$PWSHFW_VERSION.pkg -target /
  fast_finish: true

before_install:
  - echo "Pass 01 before_install"

install:
  - echo "Pass 02 install"
  # - sudo pwsh -c 'Install-Module Pester -Force'
  # - sudo pwsh -c 'Install-Module -Name PesterMatchHashtable -Confirm:$false -Force'
  # - sudo pwsh -c  "& ./install-modules.ps1 -d -dev -api ."

before_script:
  - echo "Pass 03 before_script"
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/build.ps1"
  # - pwsh -c ./scripts/os.ps1 -d -dev -api .
  # - pwsh -c "Invoke-Pester -Script ./tests/*"

script:
  - echo "Pass 04 script"
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/test.ps1"
  # - ${TRAVIS_BUILD_DIR}/build/debian/build-travis.sh
  - pwsh -c ./build.ps1 -d -dev -ProjectPath .

before_cache:
  - echo "Pass 05 before_cache"

after_success:
  - echo "Pass 06 after_success"
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/deploy.ps1"

after_falure:
  - echo "Pass 06 after_failure"
  # - pwsh -f "${env:TRAVIS_BUILD_DIR}/deploy.ps1"

before_deploy:
  - echo "Pass 07 before_deploy"

deploy:
  api_key:
    # https://docs.travis-ci.com/user/encryption-keys/
    # https://docs.travis-ci.com/user/deployment/releases/
    # curl -H "Travis-API-Version: 3" -H "Authorization: token TOKEN" https://api.travis-ci.org/repos
    # curl -H "Travis-API-Version: 3" -H "Authorization: token TOKEN" https://api.travis-ci.com/repo/cadegenn%2Fbuild.pwsh/key_pair/generated
    # TOKEN can be found on user profile page on travis-ci.org
    secure: atn1w/Sc4+3tPrrormdQKy51Tqtwbz83pJajlh28ZcnON1Dm3oAy2pzjGcLOOO7WT7uq5HvKG/EdPFNcl9x9YhI2ocHbKPNHqhn3IZVqY/+mLWQSlfx56fgPfwdmzvVDcbbqTuEGkwWZ+CnNbYwtwGvOGC6FYwCmwaVUOvHs2OtZ/M2F5nvfhQ8f/0fF2p8bPQywFx9u53L6QpuD1XFs+wqn6/HxlvlHygT3VIslsII8+hGIZe89ogZEygUqpkNOU95EbOo4gF5EESV+MDjM92nikaRyMvmZOBLWtz13HG5RqWwCxkgI3H+CfBqqdEqLO+BfsjPTJ66noJXy85//9gzk8zE/Xh7mzKYgZqAdPOdPPTA8+gy77kOjPwD/8DQI1AgHJzL3Yp8lLudSbPuDB/9jD+3C0lfUKB8c9NHacxpLlHW/+yise2ZuZFFTuoDiLnCsSaj3vfUcnzxMsrGd/oiMDLAzrq+J3GkXJ+mZfJ+xvXnzAwsbeMyE+3XPHMF4FC6asjRK+hf4tcNEob97/EbGGhJQNdwl+nmj3pn3gcnrtcHpEoUhQoNCaBi0uctsMryhzWXA8kvWBBHzk4dymFxOWdBb30HixastOB7OWegi0WC4WoJGHJhytUM+0NxiAEijnYSUM+tB0nkU3R/WBSPd8QkiqfvsToEG8vRjD+E=
  # file: "${TRAVIS_BUILD_DIR}/releases/debian/pwshfw-${TRAVIS_BUILD_VERSION}-all.deb"
  target_commitish: $TRAVIS_COMMIT # <--------both used
  tag_name: $TRAVIS_TAG # <--------both used
  file_glob: true
  file: releases/*
  overwrite: true
  skip_cleanup: true
  provider: releases
  draft: true
  prerelease: true
  on:
    repo: cadegenn/build.pwsh
    branch: develop
    tags: true
  # - provider: releases
  #   draft: false
  #   prerelease: false
  #   on:
  #     branch: master
  #     tags: true

after_deploy:
  - echo "Pass 09 after_deploy"

after_script:
  - echo "Pass 10 after_script"

